blog/urls.py
from django.urls import path, include
from blog import views

handler404 = 'blog.views.handler404'
handler505 = 'blog.views.handler500'

urlpatterns = [
    path('', views.index, name="index"),
    path('all/', views.BlogListView.as_view(), name="blogs"),
    path('blog/<int:pk>/', views.BlogDetailView.as_view(), name="blog"),

    path('new/', views.NewBlogCreateView.as_view(), name="new-blog"),

    path('comments/<int:pk>/deleted/', views.CommentDeleteView.as_view(), name='delete-comment'),
    path('comments/<int:pk>/edit/', views.UpdateCommentUpdateView.as_view(), name='update-comment'),

    path('authors/', views.AuthorListView.as_view(), name="authors"),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name="author"),

    path('author/new/', views.AuthorCreate.as_view(), name="create-author"),

    path('comments/<int:pk>', views.comment, name="comment"),

    path('signup/', views.signup, name="signup"),

    path('<int:pk>/update/', views.UpdatePostUpdateView.as_view(), name="update-post"),
]

diyblog/urls.py
import django.contrib.auth
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url="blogs/", permanent=True)),

    # path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=10000)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True,)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog', args=[str(self.id)])


class Author(models.Model):
    """Model representing name of bloggers"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(max_length=10000, blank=True)
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_of_birth = models.DateField(null=True, blank=True, default='1998-10-12')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('author', args=[str(self.id)])


class Comment(models.Model):
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey('Blog', on_delete=models.SET_NULL, null=True)
    comment = models.TextField(max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True,)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('blog', args=[str(self.blog.id)])

blog/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class AddAuthorForm(forms.Form):
    first_name = forms.CharField(max_length=100, help_text="Enter your first name")
    last_name = forms.CharField(max_length=100, help_text="Enter your last name")
    bio = forms.Textarea()
    date_of_birth = forms.DateField(help_text="Enter date of birth")

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']

        current_date = datetime.date.today()

        if date_of_birth > current_date:
            raise ValidationError(_("Cannot set future date of birth. Please set correct date"))

        return date_of_birth


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=False, help_text="Enter first name")
    last_name = forms.CharField(max_length=50, required=False, help_text="Enter last name")
    email = forms.EmailField(max_length=200, help_text="Required. Inform a valid email address")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

blog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import authenticate, login as login_auth, logout as logout_auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import CreateView

from blog.forms import SignUpForm
from blog.models import Blog, Author, Comment


def index(request):
    blogs = Blog.objects.count()
    author = Author.objects.count()
    params = {
        'blogs': blogs,
        'authors': author,
    }
    return render(request, 'blog/index.html', params)


class NewBlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = Blog
    template_name = "blog/create_new_post.html"
    success_url = '/'
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        try:
            author_object = Author.objects.get(username=self.request.user)
            form.instance.user = author_object
        except Author.DoesNotExist:
            author_object = None

        if author_object is None:
            user = self.request.user
            author_new_object = Author(first_name=user, last_name='', bio='Not updated', username=self.request.user)
            author_new_object.save()
            form.instance.user = Author.objects.get(username=user)

        form.save()
        return super(NewBlogCreateView, self).form_valid(form)


class BlogListView(generic.ListView):
    model = Blog
    template_name = 'blog/blogs.html'
    context_object_name = 'blogs'
    paginate_by = 8


class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = "blog/blog.html"
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        blog_obj = self.kwargs['pk']
        context['comments'] = Comment.objects.filter(blog=blog_obj).order_by('-timestamp')
        return context


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'blog/authors.html'
    context_object_name = 'authors'
    paginate_by = 8


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'blog/author.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['author_blogs'] = Blog.objects.all()
        return context


@login_required
def comment(request, pk=None):
    if request.method == 'POST':
        user_comment = request.POST['comment']
        user = request.user.username
        blog_instance = Blog.objects.get(id=pk)
        comment_obj = Comment(comment=user_comment, username=request.user, blog=blog_instance)
        comment_obj.save()
    return redirect(reverse('blog', kwargs={"pk": pk}))


class AuthorCreate(LoginRequiredMixin, generic.CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'bio', 'date_of_birth']
    template_name = 'blog/author_form.html'
    context_object_name = 'new_author'
    initial = {'date_of_birth': '01/01/1990'}

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not self.request.user.is_staff:
            return render(request, 'blog/unauthorized.html')
        return super(AuthorCreate, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.test_func


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('index')
            else:
                return HttpResponse("Invalid username & password")

    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


class CommentDeleteView(UserPassesTestMixin, LoginRequiredMixin, generic.DeleteView):
    success_message = "Deleted Successfully"
    model = Comment
    template_name = 'blog/comment_confirm_delete.html'
    context_object_name = 'delete_comment'
    success_url = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.username != self.request.user:
            return render(request, 'blog/unauthorized.html')
        return super(CommentDeleteView, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.test_func


class UpdateCommentUpdateView(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = Comment
    template_name = 'blog/update_comment_form.html'
    context_object_name = 'update_comment'
    fields = ['comment']

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.username != self.request.user:
            return render(request, 'blog/unauthorized.html')
        return super(UpdatePostUpdateView, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.test_func


class UpdatePostUpdateView(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = Blog
    template_name = 'blog/update_post_form.html'
    context_object_name = 'update_blog'
    fields = ['title', 'content']

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return render(request, 'blog/unauthorized.html')
        return super(UpdatePostUpdateView, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.test_func

def handler404(request, exception):
    return render(request, 'blog/pnf.html', {'exception': exception})


def handler505(request, exception):
    return render(request, 'blog/pnf.html', {'exception': exception})

templates/blog/author.html
{% extends 'base.html' %}

{% block style %}
{% endblock %}

{% block body %}

    <h5 class="vLargeTextField" style="color: orange">{{ author.first_name }} {{ author.last_name }}
        <a href="#" style="font-size: 15px; float:right"><span style="color: gray">By:</span> {{ author.last_name }}</a>
    </h5>
    <hr>
    <div class="mt-3"></div>
    <ul class="list-group list-group-flush">
        <li class="p-2 list-group-item">
            <h6>Date of Birth:</h6>
            <p>{{ author.date_of_birth }}</p>
        </li>
        <li class="p-2 list-group-item">
            <h6>Bio:</h6>
            <p>{{ author.bio|linebreaks }}</p>
        </li>
    </ul>
    <h5 class="vLargeTextField">
    {% if author.blog_set.count > 0 %}
        Blogs posts written by {{ author.first_name }} {{ author.last_name }} are:
    {% else %}
        {{ author.first_name }} {{ author.last_name }} has not written any blog posts yet.
    {% endif %}
    </h5>
    <hr>
    <ul class="list-group list-group-flush">
        {% if author.blog_set.count > 0 %}
            {% for blog in author.blog_set.all %}
                <li class="p-2 list-group-item">
                    <a href="{% url 'blog' blog.pk %}"> {{ blog.title }}</a>
                    <a style="font-size: 15px; float:right"><span style="color: gray"></span> {{ blog.timestamp }}</a>
                </li>
            {% endfor %}
        {% else %}
            <li class="p-2 list-group-item">
                <a>All blogs written by {{ author.first_name }}
                {{ author.last_name }} will be displayed here.</a>
            </li>
        {% endif %}
    </ul>


{% endblock %}

templates/blog/author_form.html
{% extends 'base.html' %}

{% block title %}New author - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}

    {% if request.user.is_staff %}
        <h5 class="vLargeTextField">Create a new author at TimeBlog
        </h5>
        <hr>
        <div class="mt-3"></div>

        <form action="#" method="post">
            {% csrf_token %}
            <ul class="list-group list-group-flush">
                {{ form.as_table }}
                <input type="submit" value="Create new author👶" class="btn btn-primary mt-1">
            </ul>
        </form>
    {% else %}
        <div class="mt-3"></div>
        <h4>Cannot create a new author, don't know why?</h4>
        <p>New authors can only be created by staff members.</p>
    {% endif %}
    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/blog/authors.html
{% extends 'base.html' %}

{% block body %}
    <h1>Welcome to TimeBlog.</h1>

    <p class="vLargeTextField">These are all bloggers active in TimeBlog.</p>
    {% block pagination %}
        {% if is_paginated %}
            <nav class="mt-3" aria-label="Page navigation example">
                <ul class="pagination pagination-sm justify-content-center">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% else %}
                            <a class="page-link" aria-label="Previous">
                                <span style="color:grey" aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
                    <li class="page-item"><a class="page-link">of</a></li>
                    <li class="page-item"><a class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                    <li class="page-item">
                        {% if page_obj.has_next %}
                            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% else %}
                            <a class="page-link" aria-label="Next">
                                <span style="color: grey" aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        {% endif %}
    {% endblock %}
    <hr>
    <div class="mt-3"></div>
    <ul class="list-group list-group-flush">

        {% for author in authors %}
            <li class="p-2 list-group-item">
                <a href="{% url 'author' author.pk %}"> {{ author.first_name }} {{ author.last_name }}</a>
            </li>

        {% endfor %}
    </ul>

{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}

{% load humanize %}

{% block body %}

    <h5 class="vLargeTextField">{{ blog.title }}
        <a href="#" style="font-size: 15px; float:right"><span style="color: gray">By:</span> {{ blog.author }}</a><br>
        <span style="color: gray; font-size: 15px; float:right">{{ blog.timestamp|naturaltime }}</span> <br>

    </h5>
    {% if blog.author == request.user %}
        <a href="{% url 'update-post' blog.pk %}" style="float: right" class="btn btn-warning pb-0 pt-0">Update post</a>
    {% endif %}

    <hr>
    <div class="mt-3"></div>
    <ul class="list-group list-group-flush">
        <li class="p-2 list-group-item">
            <p>{{ blog.content|linebreaks }}</p>
        </li>
    </ul>
    {% if blog.author == request.user %}
    {% endif %}
    <hr>
    <p>
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
           aria-controls="collapseExample">
            Comment 🥳
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body p-2" style="border: 0px">
            <div class="mb-3">
                <form method="post" action="{% url 'comment' blog.pk %}">
                    {% csrf_token %}
                    <label for="comment" class="form-label">Comment</label>
                    <textarea class="form-control" name="comment" id="comment" rows="2"></textarea>
                    <input type="submit" value="Comment" class="btn btn-success mt-1 p-1">
                </form>
            </div>
        </div>
    </div>

    <h5 style="color: orange">{{ comments|length }} Comments- </h5>
    <div class="mt-5">

        {% for comment in comments %}

            <div class="alert alert-secondary" role="alert">
                <img width="40px" height="40px" style="object-fit: cover; border-radius: 60px"
                     src="https://media.istockphoto.com/photos/silhouette-of-a-businessman-for-use-as-a-profile-picture-picture-id474001632?s=612x612">
                <span style="padding: 1%; color: blue; border: 1px solid gray">{{ comment.username }}</span> <br>
                <p class="pl-3 pt-3">{{ comment }}</p>
                <span style="font-size:13px; color: darkgrey; float:right">{{ comment.timestamp|naturaltime }}
                    {% if comment.username == request.user %}
                        <button class="btn btn-warning pb-0 pt-0" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                <u style="font-size: 13px">Options</u>
            </button>
                        <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'delete-comment' comment.pk %}">Delete</a></li>
                <li><a class="dropdown-item" href="{% url 'update-comment' comment.pk %}">Update Comment</a></li>
            </ul>
                    {% endif %}
            </span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/blogs.html
{% extends 'base.html' %}

{% load humanize %}
{% block body %}
    <h1>Welcome to TimeBlog.</h1>

    <p class="vLargeTextField">These are all blog posts created till date.</p>
        <a href="{% url 'new-blog' %}" class="btn btn-success pt-0 pb-0" style="float:right;">New blog</a>
    <strong>Create a blog today!</strong>

    {% block pagination %}
        {% if is_paginated %}
            <nav class="mt-3" aria-label="Page navigation example">
                <ul class="pagination pagination-sm justify-content-center">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% else %}
                            <a class="page-link" aria-label="Previous">
                                <span style="color:grey" aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}
                    </li>
                    <li class="page-item"><a class="page-link">{{ page_obj.number }}</a></li>
                    <li class="page-item"><a class="page-link">of</a></li>
                    <li class="page-item"><a class="page-link">{{ page_obj.paginator.num_pages }}</a></li>
                    <li class="page-item">
                        {% if page_obj.has_next %}
                            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% else %}
                            <a class="page-link" aria-label="Next">
                                <span style="color: grey" aria-hidden="true">&raquo;</span>
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        {% endif %}
    {% endblock %}
    <hr>
    <div class="mt-3"></div>
    <ul class="list-group list-group-flush">
        {% for blog in blogs %}
            <li class="p-2 list-group-item">
                <a href="{% url 'blog' blog.id %}"> {{ blog.title }}</a>
                <p style="font-size: 15px">{{ blog.timestamp|naturaltime }} - <i style="color: darkgrey"> {{ blog.comment_set.count }} Comments</i>
                </p>
                <a href="{% url 'author' blog.user.id %}" style="font-size: 15px; float:right"><span
                        style="color: gray">By:</span> {{ blog.author }}</a>
            </li>
        {% endfor %}
        <li class="list-group-item"></li>
    </ul>

{% endblock %}

templates/blog/comment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Password reset - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}


    <h5 class="vLargeTextField">Delete your comment?
    </h5>
    <hr>
    <div class="mt-3"></div>

    <form method="post" action="">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
            Are your sure you want to delete your comment
            <span style="font-size: 14px"> '{{ delete_blog }}'?</span>
        </ul>
        <input type="submit" value="Delete">
    </form>
    <div class="mt-3"></div>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/blog/create_new_post.html
{% extends 'base.html' %}

{% block title %}New blog - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}

    <h5 class="vLargeTextField">Create a new blog at TimeBlog
    </h5>
    <hr>
    <div class="mt-3"></div>

    <form action="#" method="post">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
            {{ form.as_table }}
            <tr>
                <input hidden name="author" value="{{ request.user }}" required id="id_author">
            </tr>
            <input type="submit" value="Create new post👶" class="btn btn-primary mt-1">
        </ul>
    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>Welcome to TimeBlog.</h1>


    <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'blogs' %}">Total blog posts</a></div>
            </div>
            <span class="badge bg-primary rounded-pill">{{ blogs }} posts</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'authors' %}">Total Bloggers</a></div>
            </div>
            <span class="badge bg-primary rounded-pill">{{ authors }} bloggers</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'new-blog' %}">Create a new blog</a></div>
            </div>
            <span class="badge bg-primary rounded-pill">Free</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'create-author' %}">Add a new author</a></div>
            </div>
            <span class="badge bg-primary rounded-pill">Only staff users</span>
        </li>
    </ol>


{% endblock %}

templates/blog/pnf.html
{% extends 'base.html' %}

{% block title %}Password reset - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}

    <h5 class="vLargeTextField">Page not found
    </h5>
    <hr>
    <div class="mt-3"></div>

    <ul class="list-group list-group-flush">
        The page you requested was either deleted or not found.
        <p><strong>Exception type: </strong>{{ exception }}</p>
        Go to <a href="{% url 'index' %}">homepage</a> to continue.
    </ul>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/blog/unauthorized.html
{% extends 'base.html' %}

{% block title %}Password reset - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}


        <div class="mt-3"></div>
        <h1>Unable to take your request, don't know why?</h1>
        <h5 class="vLargeTextField">Sorry, you don't have the right permissions to carry out the changes, contact admin?
<br>
<br>
<br>
<br>
{% endblock %}

templates/blog/update_comment_form.html
{% extends 'base.html' %}

{% block title %}Comment update - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}

    <h5 class="vLargeTextField">Update your comment at TimeBlog
    </h5>
    <hr>
    <div class="mt-3"></div>

    <form action="#" method="post">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
            {{ form.as_table }}
            <input type="submit" value="Update post👶" class="btn btn-primary mt-1">
        </ul>
    </form>
    <div class="mt-4"></div>

    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/blog/update_post_form.html
{% extends 'base.html' %}

{% block title %}Blog update - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

{% endblock %}
{% block body %}
    <h5 class="vLargeTextField">Update your blog at TimeBlog
    </h5>
    <hr>
    <div class="mt-3"></div>

    <form action="#" method="post">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
            {{ form.as_table }}
            <input type="submit" value="Update post👶" class="btn btn-primary mt-1">
        </ul>
    </form>
    <div class="mt-3"></div>

    <br>
    <br>
    <br>
    <br>
{% endblock %}